### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by jgroom33** [AlanWalk/Markdown-TOC#2] opened 2016-06-12 23:14 UTC
code blocks using (3) backticks ``` do not seem to be supported

Example:

# level 1 

```javascript
var a=a
```

Error: Running the contributed command:'extension.updateMarkdownToc' failed.

**Comment by AlanWalk** [comment] 2016-06-14 06:05
The problem is fixed in new version. Thank  you for your feedback.

**Closed** 2016-06-14 09:10 UTC
